import groovy.json.JsonSlurperClassic

def jsonParse(def json){
    new groovy.json.JsonSlurperClassic().parseText(json)
}
pipeline {
    agent { label 'master' }
    enviroment { 
        appName = "variable"
    }
    stages {
        stage("step 1"){
            steps{
                script{
                    sh "echo 'Hello World!!!'"
                }
            }
        }
    }
    post {
        always {
            deleteDir()
              sh "echo 'fase always'"
        }
        success {
            sh "echo 'fase success'"
        }
        failure {
            sh "echo 'fase failure'"
        }
    }
}